inherit_from: configs/img/onet.yaml
data:
  dataset: images
  path: demo
training:
  out_dir:  demo
test:
  model_file: '/home/wisrl/hynam/occupancy_networks/out/img/onet/model.pt'
generation:
  generation_dir: generation
  refinement_step: 30
  simplify_nfaces: 5000
